name: 'Build Skeletyl Firmware'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Debug Rules.mk files
        run: |
          echo "--- keyboards/axl13/my_skeletyl/rules.mk ---"
          cat keyboards/axl13/my_skeletyl/rules.mk
          echo "--- keyboards/axl13/my_skeletyl/keymaps/default/rules.mk ---"
          cat keyboards/axl13/my_skeletyl/keymaps/default/rules.mk

      - name: Compile Firmware
        run: qmk compile -kb axl13/my_skeletyl -km default VERBOSE=true

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: skeletyl-firmware
          path: axl13_my_skeletyl_default.hex
